
spring.datasource.url=JDBC:MySQL://localHost:3306/StudentDatabase
spring.datasource.username=your_name
spring.datasource.password=your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8000
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

